[platformio]
default_envs = nodemcuv2

[env]
platform = espressif8266
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.filesystem = littlefs
lib_deps =
  https://github.com/bblanchon/ArduinoJson.git#v6.21.5
  https://github.com/tzapu/WiFiManager.git
  https://github.com/knolleary/pubsubclient.git#v2.8
  https://github.com/PaulStoffregen/OneWire.git
  https://github.com/milesburton/Arduino-Temperature-Control-Library.git
  https://github.com/adafruit/DHT-sensor-library.git
  https://github.com/claws/BH1750.git
  https://github.com/adafruit/Adafruit_BME280_Library.git
  https://github.com/adafruit/Adafruit_Sensor.git
build_flags =
  -D FW_VERSION=\"0.1.0\"
  -D DEFAULT_TELEMETRY_INTERVAL_MS=15000UL
  -D DEFAULT_TCP_PORT=18830
  -D DEFAULT_HTTP_PORT=8080
  -D DEFAULT_MQTT_PORT=1883
  -D DEFAULT_I2C_SDA=4
  -D DEFAULT_I2C_SCL=5
  -D DEFAULT_DHT_PIN=12
  -D DEFAULT_ONEWIRE_PIN=14
  -D DEFAULT_HTTP_PATH=\"/api/v1/ingest/http/{device_id}\"

[env:nodemcuv2]
board = nodemcuv2

[env:d1_mini]
board = d1_mini
