package main

import (
	"bufio"
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"log"
	"net"
	"net/http"
	"net/url"
	"os"
	"strings"
	"sync"
	"sync/atomic"
	"time"
)

type config struct {
	mode           string
	baseURL        string
	gatewayAddr    string
	mqttAddr       string
	productID      string
	topicTemplate  string
	devices        int
	messages       int
	concurrency    int
	interval       time.Duration
	requestTimeout time.Duration
}

type deviceCredential struct {
	ID    string `json:"id"`
	Token string `json:"token"`
}

type loadStats struct {
	sent        atomic.Int64
	failed      atomic.Int64
	bytes       atomic.Int64
	latencyNanos atomic.Int64
}

type summary struct {
	Mode               string  `json:"mode"`
	Devices            int     `json:"devices"`
	MessagesPerDevice  int     `json:"messages_per_device"`
	TotalMessages      int64   `json:"total_messages"`
	SuccessfulMessages int64   `json:"successful_messages"`
	FailedMessages     int64   `json:"failed_messages"`
	ApproxBytes        int64   `json:"approx_bytes"`
	DurationSeconds    float64 `json:"duration_seconds"`
	MessagesPerSecond  float64 `json:"messages_per_second"`
	AverageLatencyMS   float64 `json:"average_latency_ms"`
}

func main() {
	cfg := parseFlags()
	cfg.mode = strings.ToLower(strings.TrimSpace(cfg.mode))
	if err := validateConfig(cfg); err != nil {
		log.Fatalf("invalid configuration: %v", err)
	}

	client := &http.Client{Timeout: cfg.requestTimeout}
	productID, err := ensureProduct(client, cfg)
	if err != nil {
		log.Fatalf("prepare product: %v", err)
	}
	devices, err := provisionDevices(client, cfg, productID)
	if err != nil {
		log.Fatalf("provision devices: %v", err)
	}

	stats := &loadStats{}
	stopProgress := make(chan struct{})
	go reportProgress(stopProgress, stats, int64(len(devices)*cfg.messages))

	startedAt := time.Now()
	if err := runLoad(cfg, client, devices, stats); err != nil {
		close(stopProgress)
		log.Fatalf("run load: %v", err)
	}
	close(stopProgress)

	report := buildSummary(cfg, stats, time.Since(startedAt))
	payload, err := json.MarshalIndent(report, "", "  ")
	if err != nil {
		log.Fatalf("marshal summary: %v", err)
	}
	fmt.Fprintln(os.Stdout, string(payload))

	if report.FailedMessages > 0 {
		os.Exit(1)
	}
}

func parseFlags() config {
	cfg := config{}
	flag.StringVar(&cfg.mode, "mode", "http", "load mode: http | tcp | mqtt")
	flag.StringVar(&cfg.baseURL, "base-url", "http://127.0.0.1:8080", "platform HTTP base URL")
	flag.StringVar(&cfg.gatewayAddr, "gateway-addr", "127.0.0.1:18830", "TCP gateway address")
	flag.StringVar(&cfg.mqttAddr, "mqtt-addr", "127.0.0.1:1883", "MQTT broker address")
	flag.StringVar(&cfg.productID, "product-id", "", "existing product ID; empty means auto-create")
	flag.StringVar(&cfg.topicTemplate, "topic-template", "devices/{device_id}/up", "MQTT publish topic template")
	flag.IntVar(&cfg.devices, "devices", 100, "number of devices to provision")
	flag.IntVar(&cfg.messages, "messages", 100, "telemetry messages per device")
	flag.IntVar(&cfg.concurrency, "concurrency", 32, "max concurrent active devices")
	flag.DurationVar(&cfg.interval, "interval", 0, "optional delay between telemetry messages")
	flag.DurationVar(&cfg.requestTimeout, "timeout", 10*time.Second, "dial/request timeout")
	flag.Parse()
	return cfg
}

func validateConfig(cfg config) error {
	switch strings.ToLower(strings.TrimSpace(cfg.mode)) {
	case "http", "tcp", "mqtt":
	default:
		return fmt.Errorf("unsupported mode %q", cfg.mode)
	}
	if cfg.devices <= 0 {
		return errors.New("devices must be > 0")
	}
	if cfg.messages <= 0 {
		return errors.New("messages must be > 0")
	}
	if cfg.concurrency <= 0 {
		return errors.New("concurrency must be > 0")
	}
	return nil
}

func ensureProduct(client *http.Client, cfg config) (string, error) {
	if strings.TrimSpace(cfg.productID) != "" {
		return strings.TrimSpace(cfg.productID), nil
	}

	body := map[string]any{
		"name":        fmt.Sprintf("loadgen-%s-%d", cfg.mode, time.Now().Unix()),
		"description": "autogenerated benchmark product",
		"access_profile": map[string]any{
			"transport":      modeTransport(cfg.mode),
			"protocol":       modeProtocol(cfg.mode),
			"ingest_mode":    modeIngest(cfg.mode),
			"payload_format": "json_values",
			"auth_mode":      "token",
			"topic":          mqttPublishTopic(cfg.topicTemplate, "{device_id}"),
		},
		"thing_model": map[string]any{
			"properties": []map[string]any{
				{"identifier": "temperature", "name": "Temperature", "data_type": "float", "access_mode": "r"},
				{"identifier": "humidity", "name": "Humidity", "data_type": "float", "access_mode": "r"},
			},
		},
	}

	var response struct {
		ID string `json:"id"`
	}
	if err := doJSON(client, http.MethodPost, strings.TrimRight(cfg.baseURL, "/")+"/api/v1/products", body, &response); err != nil {
		return "", err
	}
	if response.ID == "" {
		return "", errors.New("product creation returned empty id")
	}
	return response.ID, nil
}

func provisionDevices(client *http.Client, cfg config, productID string) ([]deviceCredential, error) {
	devices := make([]deviceCredential, 0, cfg.devices)
	baseURL := strings.TrimRight(cfg.baseURL, "/")
	for index := 0; index < cfg.devices; index++ {
		body := map[string]any{
			"name":       fmt.Sprintf("%s-load-%06d", cfg.mode, index),
			"product_id": productID,
			"tags": map[string]string{
				"source": "loadgen",
				"mode":   cfg.mode,
			},
		}
		var device deviceCredential
		if err := doJSON(client, http.MethodPost, baseURL+"/api/v1/devices", body, &device); err != nil {
			return nil, err
		}
		if device.ID == "" || device.Token == "" {
			return nil, fmt.Errorf("device provisioning returned incomplete credentials: %+v", device)
		}
		devices = append(devices, device)
	}
	return devices, nil
}

func doJSON(client *http.Client, method, target string, payload any, out any) error {
	data, err := json.Marshal(payload)
	if err != nil {
		return err
	}
	req, err := http.NewRequest(method, target, bytes.NewReader(data))
	if err != nil {
		return err
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := client.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		body, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("%s %s returned %d: %s", method, target, resp.StatusCode, strings.TrimSpace(string(body)))
	}
	if out == nil {
		return nil
	}
	return json.NewDecoder(resp.Body).Decode(out)
}

func runLoad(cfg config, client *http.Client, devices []deviceCredential, stats *loadStats) error {
	sem := make(chan struct{}, cfg.concurrency)
	var wg sync.WaitGroup

	for _, device := range devices {
		device := device
		sem <- struct{}{}
		wg.Add(1)
		go func() {
			defer func() {
				<-sem
				wg.Done()
			}()

			switch cfg.mode {
			case "http":
				runHTTPDevice(cfg, client, device, stats)
			case "tcp":
				runTCPDevice(cfg, device, stats)
			case "mqtt":
				runMQTTDevice(cfg, device, stats)
			}
		}()
	}

	wg.Wait()
	return nil
}

func runHTTPDevice(cfg config, client *http.Client, device deviceCredential, stats *loadStats) {
	target := strings.TrimRight(cfg.baseURL, "/") + "/api/v1/ingest/http/" + url.PathEscape(device.ID)
	for index := 0; index < cfg.messages; index++ {
		payload := map[string]any{
			"token": device.Token,
			"values": map[string]any{
				"temperature": 20.0 + float64(index%15),
				"humidity":    40 + (index % 30),
			},
		}
		data, err := json.Marshal(payload)
		if err != nil {
			recordFailure(stats, 1)
			continue
		}

		startedAt := time.Now()
		req, err := http.NewRequest(http.MethodPost, target, bytes.NewReader(data))
		if err != nil {
			recordFailure(stats, 1)
			continue
		}
		req.Header.Set("Content-Type", "application/json")

		resp, err := client.Do(req)
		if err != nil {
			recordFailure(stats, 1)
			sleepInterval(cfg.interval)
			continue
		}
		_, _ = io.Copy(io.Discard, resp.Body)
		resp.Body.Close()
		if resp.StatusCode != http.StatusAccepted {
			recordFailure(stats, 1)
			sleepInterval(cfg.interval)
			continue
		}

		recordSuccess(stats, int64(len(data)), time.Since(startedAt))
		sleepInterval(cfg.interval)
	}
}

func runTCPDevice(cfg config, device deviceCredential, stats *loadStats) {
	conn, err := net.DialTimeout("tcp", cfg.gatewayAddr, cfg.requestTimeout)
	if err != nil {
		recordFailure(stats, int64(cfg.messages))
		return
	}
	defer conn.Close()

	reader := bufio.NewReader(conn)
	if err := writeTCPLine(conn, map[string]any{
		"type":      "auth",
		"device_id": device.ID,
		"token":     device.Token,
	}); err != nil {
		recordFailure(stats, int64(cfg.messages))
		return
	}
	if _, err := readTCPLine(conn, reader, cfg.requestTimeout); err != nil {
		recordFailure(stats, int64(cfg.messages))
		return
	}

	for index := 0; index < cfg.messages; index++ {
		payload := map[string]any{
			"type": "telemetry",
			"values": map[string]any{
				"temperature": 20.0 + float64(index%15),
				"humidity":    40 + (index % 30),
			},
		}
		data, err := json.Marshal(payload)
		if err != nil {
			recordFailure(stats, 1)
			continue
		}
		startedAt := time.Now()
		if err := conn.SetWriteDeadline(time.Now().Add(cfg.requestTimeout)); err != nil {
			recordFailure(stats, 1)
			continue
		}
		if _, err := conn.Write(append(data, '\n')); err != nil {
			recordFailure(stats, int64(cfg.messages-index))
			return
		}
		recordSuccess(stats, int64(len(data)), time.Since(startedAt))
		sleepInterval(cfg.interval)
	}
}

func runMQTTDevice(cfg config, device deviceCredential, stats *loadStats) {
	conn, err := net.DialTimeout("tcp", cfg.mqttAddr, cfg.requestTimeout)
	if err != nil {
		recordFailure(stats, int64(cfg.messages))
		return
	}
	defer conn.Close()

	clientID := "loadgen-" + device.ID
	if err := conn.SetWriteDeadline(time.Now().Add(cfg.requestTimeout)); err != nil {
		recordFailure(stats, int64(cfg.messages))
		return
	}
	if _, err := conn.Write(buildMQTTConnectPacket(clientID, device.ID, device.Token)); err != nil {
		recordFailure(stats, int64(cfg.messages))
		return
	}
	packetType, payload, err := readMQTTPacket(conn, cfg.requestTimeout)
	if err != nil {
		recordFailure(stats, int64(cfg.messages))
		return
	}
	if packetType != 2 || len(payload) < 2 || payload[1] != 0 {
		recordFailure(stats, int64(cfg.messages))
		return
	}

	topic := mqttPublishTopic(cfg.topicTemplate, device.ID)
	for index := 0; index < cfg.messages; index++ {
		message := map[string]any{
			"values": map[string]any{
				"temperature": 20.0 + float64(index%15),
				"humidity":    40 + (index % 30),
			},
		}
		data, err := json.Marshal(message)
		if err != nil {
			recordFailure(stats, 1)
			continue
		}
		startedAt := time.Now()
		if err := conn.SetWriteDeadline(time.Now().Add(cfg.requestTimeout)); err != nil {
			recordFailure(stats, 1)
			continue
		}
		if _, err := conn.Write(buildMQTTPublishPacket(topic, data)); err != nil {
			recordFailure(stats, int64(cfg.messages-index))
			return
		}
		recordSuccess(stats, int64(len(data)), time.Since(startedAt))
		sleepInterval(cfg.interval)
	}

	_, _ = conn.Write([]byte{0xE0, 0x00})
}

func writeTCPLine(conn net.Conn, payload any) error {
	data, err := json.Marshal(payload)
	if err != nil {
		return err
	}
	if _, err := conn.Write(append(data, '\n')); err != nil {
		return err
	}
	return nil
}

func readTCPLine(conn net.Conn, reader *bufio.Reader, timeout time.Duration) ([]byte, error) {
	if err := conn.SetReadDeadline(time.Now().Add(timeout)); err != nil {
		return nil, err
	}
	return reader.ReadBytes('\n')
}

func buildMQTTConnectPacket(clientID, username, password string) []byte {
	var variable bytes.Buffer
	writeMQTTString(&variable, "MQTT")
	variable.WriteByte(0x04)
	variable.WriteByte(0xC2)
	variable.WriteByte(0x00)
	variable.WriteByte(0x3C)
	writeMQTTString(&variable, clientID)
	writeMQTTString(&variable, username)
	writeMQTTString(&variable, password)

	var packet bytes.Buffer
	packet.WriteByte(0x10)
	packet.Write(encodeMQTTRemainingLength(variable.Len()))
	packet.Write(variable.Bytes())
	return packet.Bytes()
}

func buildMQTTPublishPacket(topic string, payload []byte) []byte {
	var variable bytes.Buffer
	writeMQTTString(&variable, topic)
	variable.Write(payload)

	var packet bytes.Buffer
	packet.WriteByte(0x30)
	packet.Write(encodeMQTTRemainingLength(variable.Len()))
	packet.Write(variable.Bytes())
	return packet.Bytes()
}

func readMQTTPacket(conn net.Conn, timeout time.Duration) (byte, []byte, error) {
	if err := conn.SetReadDeadline(time.Now().Add(timeout)); err != nil {
		return 0, nil, err
	}

	header := make([]byte, 1)
	if _, err := io.ReadFull(conn, header); err != nil {
		return 0, nil, err
	}

	remaining, err := readMQTTRemainingLength(conn)
	if err != nil {
		return 0, nil, err
	}
	payload := make([]byte, remaining)
	if _, err := io.ReadFull(conn, payload); err != nil {
		return 0, nil, err
	}
	return header[0] >> 4, payload, nil
}

func readMQTTRemainingLength(conn net.Conn) (int, error) {
	multiplier := 1
	value := 0
	buffer := make([]byte, 1)
	for {
		if _, err := io.ReadFull(conn, buffer); err != nil {
			return 0, err
		}
		value += int(buffer[0]&127) * multiplier
		if buffer[0]&128 == 0 {
			return value, nil
		}
		multiplier *= 128
		if multiplier > 128*128*128 {
			return 0, errors.New("invalid mqtt remaining length")
		}
	}
}

func writeMQTTString(buffer *bytes.Buffer, value string) {
	buffer.WriteByte(byte(len(value) >> 8))
	buffer.WriteByte(byte(len(value)))
	buffer.WriteString(value)
}

func encodeMQTTRemainingLength(length int) []byte {
	result := make([]byte, 0, 4)
	for {
		digit := byte(length % 128)
		length /= 128
		if length > 0 {
			digit |= 0x80
		}
		result = append(result, digit)
		if length == 0 {
			break
		}
	}
	return result
}

func mqttPublishTopic(template, deviceID string) string {
	topic := strings.TrimSpace(template)
	if topic == "" {
		topic = "devices/{device_id}/up"
	}
	topic = strings.ReplaceAll(topic, "{device_id}", deviceID)
	if strings.ContainsAny(topic, "+#") {
		topic = "devices/" + deviceID + "/up"
	}
	if !strings.HasSuffix(topic, "/up") {
		topic = strings.TrimRight(topic, "/") + "/up"
	}
	return topic
}

func modeTransport(mode string) string {
	switch mode {
	case "tcp":
		return "tcp"
	case "mqtt":
		return "mqtt"
	default:
		return "http"
	}
}

func modeProtocol(mode string) string {
	switch mode {
	case "tcp":
		return "tcp_json"
	case "mqtt":
		return "mqtt_json"
	default:
		return "http_json"
	}
}

func modeIngest(mode string) string {
	switch mode {
	case "tcp":
		return "gateway_tcp"
	case "mqtt":
		return "broker_mqtt"
	default:
		return "http_push"
	}
}

func sleepInterval(interval time.Duration) {
	if interval > 0 {
		time.Sleep(interval)
	}
}

func recordSuccess(stats *loadStats, bytes int64, latency time.Duration) {
	stats.sent.Add(1)
	stats.bytes.Add(bytes)
	stats.latencyNanos.Add(latency.Nanoseconds())
}

func recordFailure(stats *loadStats, count int64) {
	stats.failed.Add(count)
}

func reportProgress(stop <-chan struct{}, stats *loadStats, total int64) {
	ticker := time.NewTicker(5 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-stop:
			return
		case <-ticker.C:
			sent := stats.sent.Load()
			failed := stats.failed.Load()
			log.Printf("progress sent=%d failed=%d total=%d", sent, failed, total)
		}
	}
}

func buildSummary(cfg config, stats *loadStats, duration time.Duration) summary {
	success := stats.sent.Load()
	failures := stats.failed.Load()
	total := int64(cfg.devices * cfg.messages)
	durationSeconds := duration.Seconds()
	if durationSeconds <= 0 {
		durationSeconds = 1
	}

	averageLatency := 0.0
	if success > 0 {
		averageLatency = float64(stats.latencyNanos.Load()) / float64(success) / float64(time.Millisecond)
	}

	return summary{
		Mode:               cfg.mode,
		Devices:            cfg.devices,
		MessagesPerDevice:  cfg.messages,
		TotalMessages:      total,
		SuccessfulMessages: success,
		FailedMessages:     failures,
		ApproxBytes:        stats.bytes.Load(),
		DurationSeconds:    durationSeconds,
		MessagesPerSecond:  float64(success) / durationSeconds,
		AverageLatencyMS:   averageLatency,
	}
}
